version: "3.9"
services:
  github-webhook-listener:
    image: jorensynaevetm/github-webhook-listener
    ports:
      - "8000:8000"
    environment:
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - CANVAS_API_KEY=${CANVAS_API_KEY}
