version: "3.9"
services:
  github-webhook-listener:
    image: jorensynaevetm/github-webhook-listener
    ports:
      - "8000:8000"
    environment:
      - CG_PASSWORD=${CG_PASSWORD}
      - CG_USERNAME=${CG_USERNAME}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
