version = 0.1
[default.deploy.parameters]
stack_name = "grader-cloud"
resolve_s3 = true
s3_prefix = "grader-cloud"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "DevState=\"local\""
