name: Okteto Flask REST API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set context to Okteto Cloud
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_AUTOMATION_TOKEN }}

    - name: Activate application namespace
      uses: okteto/namespace@latest
      with:
        namespace: jorensynaevetm

    - name: Build and deploy application image to Okteto
      if: ${{ github.event_name == 'push' }}
      uses: okteto/deploy-stack@latest
      with:
        name: github-webhook-listener
        build: true